name: SPIT
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.24.3
  - pandas=2.1.1
  - pytables
  - python=3.10
  - scikit-learn=1.3.1
  - scikit-image
  - fastparquet
  - trackpy
  - h5py
  - pyyaml
  - pip
  - seaborn
  - matplotlib=3.7.3
  - scipy=1.11.2
  - dask
  - hdbscan
  - tqdm=4.66.1
  - pyqt
  - numba=0.58.0
  - spyder
  - colorama
  - jupyterlab
  - snappy
  - tifffile
  - read-roi
  - pip:
    - opencv-python
    - lmfit==1.2.2
    - sphinx-rtd-theme
    - naclib
